
Answer.delete_all
Keyword.delete_all
Officer.delete_all
Question.delete_all
Rso.delete_all


Answer.create!([
  {id: 1, answer_title: "Yes", question_id: 1, position: 1, response_id: 1},
  {id: 2, answer_title: "No", question_id: 1, position: 2, response_id: nil},
  {id: 3, answer_title: "Yes", question_id: 2, position: 1, response_id: nil},
  {id: 4, answer_title: "Somewhat", question_id: 2, position: 2, response_id: 1},
  {id: 5, answer_title: "No", question_id: 2, position: 3, response_id: nil},
  {id: 6, answer_title: "Introverted", question_id: 4, position: 1, response_id: nil},
  {id: 7, answer_title: "Extroverted", question_id: 4, position: 2, response_id: nil},
  {id: 8, answer_title: "Somewhere in between", question_id: 4, position: 3, response_id: 1},
  {id: 9, answer_title: "Hanging out with friends", question_id: 5, position: 1, response_id: nil},
  {id: 10, answer_title: "Watching Netflix, gaming, being lazy, etc.", question_id: 5, position: 2, response_id: nil},
  {id: 11, answer_title: "Working on a personal project", question_id: 5, position: 3, response_id: 1},
  {id: 12, answer_title: "The theme", question_id: 6, position: 1, response_id: nil},
  {id: 13, answer_title: "The community of people", question_id: 6, position: 2, response_id: 1},
  {id: 14, answer_title: "The advisor", question_id: 6, position: 3, response_id: nil},
  {id: 15, answer_title: "Yes", question_id: 7, position: 1, response_id: 1},
  {id: 16, answer_title: "No", question_id: 7, position: 2, response_id: nil},
  {id: 17, answer_title: "Yes, because I've done creative things in the past", question_id: 8, position: 1, response_id: nil},
  {id: 18, answer_title: "Yes, because I'm curious", question_id: 8, position: 2, response_id: 1},
  {id: 19, answer_title: "No", question_id: 8, position: 3, response_id: nil},
  {id: 20, answer_title: "Yes, and I'm super nerdy", question_id: 9, position: 1, response_id: nil},
  {id: 21, answer_title: "Yes, but I'm not super nerdy", question_id: 9, position: 2, response_id: 1},
  {id: 22, answer_title: "No", question_id: 9, position: 3, response_id: nil},
  {id: 23, answer_title: "Yes", question_id: 10, position: 1, response_id: 1},
  {id: 24, answer_title: "No", question_id: 10, position: 2, response_id: nil},
  {id: 25, answer_title: "Yes", question_id: 11, position: 1, response_id: nil},
  {id: 26, answer_title: "No", question_id: 11, position: 2, response_id: 1},
  {id: 27, answer_title: "Yes", question_id: 12, position: 1, response_id: nil},
  {id: 28, answer_title: "Not yet. I'd like to get more involved.", question_id: 12, position: 2, response_id: 1},
  {id: 29, answer_title: "No", question_id: 12, position: 3, response_id: nil},
  {id: 30, answer_title: "Yes", question_id: 13, position: 1, response_id: nil},
  {id: 31, answer_title: "No", question_id: 13, position: 2, response_id: 1}
])
Keyword.create!([
  {id: 1, keyword: "Cooking", weight: 9, answer_id: 1},
  {id: 2, keyword: "Baking", weight: 6, answer_id: 1},
  {id: 4, keyword: "Making", weight: 5, answer_id: nil},
  {id: 5, keyword: "Cooking", weight: 5, answer_id: nil},
  {id: 6, keyword: "Baking", weight: 8, answer_id: nil},
  {id: 7, keyword: "Restaurants", weight: 8, answer_id: 2},
  {id: 17, keyword: "Not Social", weight: 2, answer_id: 8},
  {id: 19, keyword: "Not Social", weight: 6, answer_id: 6},
  {id: 20, keyword: "Strong Community", weight: 6, answer_id: 7},
  {id: 21, keyword: "Strong Community", weight: 3, answer_id: nil},
  {id: 22, keyword: "Making", weight: 5, answer_id: nil},
  {id: 23, keyword: "Restaurants", weight: 2, answer_id: nil},
  {id: 24, keyword: "Strong Community", weight: 8, answer_id: 9},
  {id: 34, keyword: "Advisor", weight: 10, answer_id: nil},
  {id: 35, keyword: "Making", weight: 2, answer_id: nil},
  {id: 64, keyword: "Active", weight: 3, answer_id: nil},
  {id: 65, keyword: "Olympics", weight: 5, answer_id: nil},
  {id: 66, keyword: "Sports", weight: 4, answer_id: nil},
  {id: 67, keyword: "Biology", weight: 10, answer_id: nil},
  {id: 68, keyword: "Science", weight: 3, answer_id: nil},
  {id: 70, keyword: "Strong Community", weight: 5, answer_id: nil},
  {id: 73, keyword: "Activism", weight: 5, answer_id: nil},
  {id: 74, keyword: "Strong Community", weight: 5, answer_id: nil},
  {id: 75, keyword: "Clear Purpose", weight: 3, answer_id: nil},
  {id: 76, keyword: "Major-focused", weight: 5, answer_id: nil},
  {id: 77, keyword: "Engineering", weight: 8, answer_id: nil},
  {id: 78, keyword: "Technology", weight: 8, answer_id: nil},
  {id: 79, keyword: "Science", weight: 7, answer_id: nil},
  {id: 80, keyword: "Nerdy", weight: 3, answer_id: nil},
  {id: 81, keyword: "Creative", weight: 4, answer_id: nil},
  {id: 82, keyword: "Creative - Experienced", weight: 4, answer_id: nil},
  {id: 83, keyword: "Creative - Inexperienced", weight: 2, answer_id: nil},
  {id: 84, keyword: "Self-directed", weight: 3, answer_id: nil},
  {id: 85, keyword: "Technology", weight: 1, answer_id: nil},
  {id: 86, keyword: "Activism", weight: 4, answer_id: nil},
  {id: 87, keyword: "Outdoors", weight: 5, answer_id: nil},
  {id: 88, keyword: "Clear Purpose", weight: 6, answer_id: nil},
  {id: 89, keyword: "Science", weight: 2, answer_id: nil},
  {id: 90, keyword: "Biology", weight: 1, answer_id: nil},
  {id: 91, keyword: "Gaming", weight: 10, answer_id: nil},
  {id: 92, keyword: "Technology", weight: 4, answer_id: nil},
  {id: 93, keyword: "Indoors", weight: 3, answer_id: nil},
  {id: 94, keyword: "Strong Community", weight: 2, answer_id: nil},
  {id: 95, keyword: "Indoors", weight: 4, answer_id: nil},
  {id: 96, keyword: "Active", weight: 4, answer_id: nil},
  {id: 97, keyword: "Olympics", weight: 2, answer_id: nil},
  {id: 98, keyword: "Sports", weight: 4, answer_id: nil},
  {id: 99, keyword: "Strong Community", weight: 4, answer_id: nil},
  {id: 100, keyword: "Science", weight: 3, answer_id: nil},
  {id: 101, keyword: "Restaurants", weight: 1, answer_id: nil},
  {id: 102, keyword: "Creative", weight: 3, answer_id: nil},
  {id: 103, keyword: "Major-focused", weight: 4, answer_id: nil},
  {id: 106, keyword: "Making", weight: 7, answer_id: 1},
  {id: 107, keyword: "Making", weight: 5, answer_id: nil},
  {id: 108, keyword: "Cooking", weight: 5, answer_id: nil},
  {id: 109, keyword: "Baking", weight: 8, answer_id: nil},
  {id: 110, keyword: "Restaurants", weight: 8, answer_id: 2},
  {id: 112, keyword: "Science", weight: 8, answer_id: 3},
  {id: 113, keyword: "Biology", weight: 2, answer_id: 3},
  {id: 114, keyword: "Chemistry", weight: 2, answer_id: 3},
  {id: 115, keyword: "Physics", weight: 2, answer_id: 3},
  {id: 116, keyword: "Science", weight: 4, answer_id: 4},
  {id: 117, keyword: "Biology", weight: 1, answer_id: 4},
  {id: 118, keyword: "Chemistry", weight: 1, answer_id: 4},
  {id: 119, keyword: "Physics", weight: 1, answer_id: 4},
  {id: 121, keyword: "Strong Community", weight: 2, answer_id: 8},
  {id: 124, keyword: "Strong Community", weight: 3, answer_id: nil},
  {id: 125, keyword: "Making", weight: 5, answer_id: nil},
  {id: 126, keyword: "Restaurants", weight: 2, answer_id: nil},
  {id: 127, keyword: "Strong Community", weight: 8, answer_id: 9},
  {id: 129, keyword: "Not Social", weight: 4, answer_id: 10},
  {id: 130, keyword: "Lazy", weight: 6, answer_id: 10},
  {id: 131, keyword: "Creative", weight: 6, answer_id: 11},
  {id: 132, keyword: "Making", weight: 5, answer_id: 11},
  {id: 133, keyword: "Self-directed", weight: 7, answer_id: 11},
  {id: 134, keyword: "Strong Community", weight: 10, answer_id: 13},
  {id: 135, keyword: "Clear Purpose", weight: 10, answer_id: 12},
  {id: 136, keyword: "Great Advisor", weight: 10, answer_id: 14},
  {id: 137, keyword: "Advisor", weight: 10, answer_id: nil},
  {id: 138, keyword: "Making", weight: 2, answer_id: nil},
  {id: 139, keyword: "Gaming", weight: 3, answer_id: 10},
  {id: 140, keyword: "Nerdy", weight: 8, answer_id: 20},
  {id: 141, keyword: "Technology", weight: 8, answer_id: 20},
  {id: 142, keyword: "Computers", weight: 8, answer_id: 20},
  {id: 143, keyword: "Science", weight: 1, answer_id: 20},
  {id: 144, keyword: "Science", weight: 1, answer_id: 21},
  {id: 145, keyword: "Technology", weight: 8, answer_id: 21},
  {id: 146, keyword: "Computers", weight: 8, answer_id: 21},
  {id: 147, keyword: "Engineering", weight: 8, answer_id: 20},
  {id: 148, keyword: "Engineering", weight: 8, answer_id: 21},
  {id: 149, keyword: "Humanities", weight: 4, answer_id: 22},
  {id: 150, keyword: "Art", weight: 4, answer_id: 22},
  {id: 151, keyword: "Sports", weight: 5, answer_id: 15},
  {id: 152, keyword: "Active", weight: 10, answer_id: 15},
  {id: 153, keyword: "Outdoors", weight: 3, answer_id: 15},
  {id: 154, keyword: "Lazy", weight: 5, answer_id: 16},
  {id: 155, keyword: "Indoors", weight: 2, answer_id: 16},
  {id: 156, keyword: "Creative", weight: 7, answer_id: 17},
  {id: 157, keyword: "Creative - Experienced", weight: 7, answer_id: 17},
  {id: 158, keyword: "Creative", weight: 7, answer_id: 18},
  {id: 159, keyword: "Creative - Inexperienced", weight: 7, answer_id: 18},
  {id: 160, keyword: "Art", weight: 3, answer_id: 17},
  {id: 161, keyword: "Making", weight: 3, answer_id: 17},
  {id: 162, keyword: "Self-directed", weight: 2, answer_id: 17},
  {id: 163, keyword: "Curious", weight: 3, answer_id: 18},
  {id: 164, keyword: "Olympics", weight: 10, answer_id: 23},
  {id: 165, keyword: "Sports", weight: 4, answer_id: 23},
  {id: 166, keyword: "Competitive", weight: 4, answer_id: 23},
  {id: 167, keyword: "Active", weight: 3, answer_id: nil},
  {id: 168, keyword: "Olympics", weight: 5, answer_id: nil},
  {id: 169, keyword: "Sports", weight: 4, answer_id: nil},
  {id: 170, keyword: "Biology", weight: 10, answer_id: nil},
  {id: 171, keyword: "Science", weight: 3, answer_id: nil},
  {id: 172, keyword: "Major-focused", weight: 10, answer_id: 25},
  {id: 173, keyword: "Strong Community", weight: 5, answer_id: nil},
  {id: 174, keyword: "Activism", weight: 10, answer_id: 27},
  {id: 175, keyword: "Activism", weight: 10, answer_id: 28},
  {id: 176, keyword: "Activism", weight: 5, answer_id: nil},
  {id: 177, keyword: "Strong Community", weight: 5, answer_id: nil},
  {id: 178, keyword: "Clear Purpose", weight: 3, answer_id: nil},
  {id: 179, keyword: "Major-focused", weight: 5, answer_id: nil},
  {id: 180, keyword: "Engineering", weight: 8, answer_id: nil},
  {id: 181, keyword: "Technology", weight: 8, answer_id: nil},
  {id: 182, keyword: "Science", weight: 7, answer_id: nil},
  {id: 183, keyword: "Nerdy", weight: 3, answer_id: nil},
  {id: 184, keyword: "Creative", weight: 4, answer_id: nil},
  {id: 185, keyword: "Creative - Experienced", weight: 4, answer_id: nil},
  {id: 186, keyword: "Creative - Inexperienced", weight: 2, answer_id: nil},
  {id: 187, keyword: "Self-directed", weight: 3, answer_id: nil},
  {id: 188, keyword: "Technology", weight: 1, answer_id: nil},
  {id: 189, keyword: "Activism", weight: 4, answer_id: nil},
  {id: 190, keyword: "Outdoors", weight: 5, answer_id: nil},
  {id: 191, keyword: "Clear Purpose", weight: 6, answer_id: nil},
  {id: 192, keyword: "Science", weight: 2, answer_id: nil},
  {id: 193, keyword: "Biology", weight: 1, answer_id: nil},
  {id: 194, keyword: "Gaming", weight: 10, answer_id: nil},
  {id: 195, keyword: "Technology", weight: 4, answer_id: nil},
  {id: 196, keyword: "Indoors", weight: 3, answer_id: nil},
  {id: 197, keyword: "Strong Community", weight: 2, answer_id: nil},
  {id: 198, keyword: "Indoors", weight: 4, answer_id: nil},
  {id: 199, keyword: "Active", weight: 4, answer_id: nil},
  {id: 200, keyword: "Olympics", weight: 2, answer_id: nil},
  {id: 201, keyword: "Sports", weight: 4, answer_id: nil},
  {id: 202, keyword: "Strong Community", weight: 4, answer_id: nil},
  {id: 203, keyword: "Science", weight: 3, answer_id: nil},
  {id: 204, keyword: "Restaurants", weight: 1, answer_id: nil},
  {id: 205, keyword: "Creative", weight: 3, answer_id: nil},
  {id: 206, keyword: "Major-focused", weight: 4, answer_id: nil},
  {id: 207, keyword: "Art", weight: 4, answer_id: 5},
  {id: 208, keyword: "Humanities", weight: 3, answer_id: 5},
  {id: 210, keyword: "Competitive", weight: 4, answer_id: nil},
  {id: 211, keyword: "Active", weight: 6, answer_id: nil},
  {id: 212, keyword: "Sports", weight: 3, answer_id: nil},
  {id: 213, keyword: "Outdoors", weight: 4, answer_id: nil},
  {id: 214, keyword: "Olympics", weight: 6, answer_id: nil},
  {id: 215, keyword: "Technology", weight: 7, answer_id: nil},
  {id: 216, keyword: "Science", weight: 3, answer_id: nil},
  {id: 217, keyword: "Nerdy", weight: 4, answer_id: nil},
  {id: 218, keyword: "Engineering", weight: 2, answer_id: nil},
  {id: 219, keyword: "Indoors", weight: 2, answer_id: nil},
  {id: 220, keyword: "Making", weight: 3, answer_id: nil},
  {id: 221, keyword: "Science", weight: 5, answer_id: nil},
  {id: 222, keyword: "Biology", weight: 10, answer_id: nil},
  {id: 223, keyword: "Major-focused", weight: 4, answer_id: nil},
  {id: 224, keyword: "Computers", weight: 7, answer_id: nil},
  {id: 225, keyword: "Major-focused", weight: 4, answer_id: nil},
  {id: 226, keyword: "Activism", weight: 10, answer_id: nil},
  {id: 227, keyword: "Strong Community", weight: 7, answer_id: nil},
  {id: 228, keyword: "Engineering", weight: 10, answer_id: nil},
  {id: 229, keyword: "Science", weight: 10, answer_id: nil},
  {id: 230, keyword: "Great Advisor", weight: 10, answer_id: nil},
  {id: 231, keyword: "Physics", weight: 7, answer_id: nil},
  {id: 232, keyword: "Chemistry", weight: 7, answer_id: nil},
  {id: 233, keyword: "Technology", weight: 7, answer_id: nil},
  {id: 234, keyword: "Computers", weight: 3, answer_id: nil},
  {id: 235, keyword: "Nerdy", weight: 4, answer_id: nil},
  {id: 236, keyword: "Computers", weight: 5, answer_id: nil},
  {id: 237, keyword: "Creative", weight: 5, answer_id: nil},
  {id: 238, keyword: "Creative - Inexperienced", weight: 6, answer_id: nil},
  {id: 239, keyword: "Creative - Experienced", weight: 6, answer_id: nil},
  {id: 240, keyword: "Art", weight: 7, answer_id: nil},
  {id: 241, keyword: "Making", weight: 3, answer_id: nil},
  {id: 242, keyword: "Technology", weight: 2, answer_id: nil},
  {id: 243, keyword: "Biology", weight: 5, answer_id: nil},
  {id: 245, keyword: "Activism", weight: 7, answer_id: nil},
  {id: 246, keyword: "Outdoors", weight: 8, answer_id: nil},
  {id: 247, keyword: "Science", weight: 6, answer_id: nil},
  {id: 248, keyword: "Major-focused", weight: 5, answer_id: nil},
  {id: 249, keyword: "Strong Community", weight: 3, answer_id: nil},
  {id: 250, keyword: "Lazy", weight: 10, answer_id: nil},
  {id: 251, keyword: "Gaming", weight: 10, answer_id: nil},
  {id: 252, keyword: "Competitive", weight: 9, answer_id: nil},
  {id: 253, keyword: "Nerdy", weight: 9, answer_id: nil},
  {id: 254, keyword: "Active", weight: 9, answer_id: nil},
  {id: 255, keyword: "Strong Community", weight: 9, answer_id: nil},
  {id: 256, keyword: "Competitive", weight: 4, answer_id: nil},
  {id: 257, keyword: "Clear Purpose", weight: 5, answer_id: nil},
  {id: 258, keyword: "Sports", weight: 6, answer_id: nil},
  {id: 259, keyword: "Indoors", weight: 7, answer_id: nil},
  {id: 260, keyword: "Major-focused", weight: 5, answer_id: nil},
  {id: 261, keyword: "Science", weight: 4, answer_id: nil},
  {id: 262, keyword: "Baking", weight: 5, answer_id: nil},
  {id: 263, keyword: "Cooking", weight: 5, answer_id: nil},
  {id: 264, keyword: "Restaurants", weight: 3, answer_id: nil},
  {id: 265, keyword: "Outdoors", weight: 5, answer_id: nil},
  {id: 267, keyword: "Science", weight: 4, answer_id: nil},
  {id: 268, keyword: "Active", weight: 1, answer_id: nil},
  {id: 269, keyword: "Major-focused", weight: 4, answer_id: nil},
  {id: 270, keyword: "Biology", weight: 10, answer_id: nil},
  {id: 271, keyword: "Science", weight: 7, answer_id: nil},
  {id: 272, keyword: "Clear Purpose", weight: 3, answer_id: nil},
  {id: 273, keyword: "Clear Purpose", weight: 10, answer_id: nil},
  {id: 274, keyword: "Gaming", weight: 5, answer_id: nil},
  {id: 275, keyword: "Nerdy", weight: 7, answer_id: nil},
  {id: 276, keyword: "Active", weight: 3, answer_id: nil},
  {id: 277, keyword: "Competitive", weight: 6, answer_id: nil},
  {id: 278, keyword: "Clear Purpose", weight: 7, answer_id: nil},
  {id: 279, keyword: "Sports", weight: 6, answer_id: nil},
  {id: 280, keyword: "Active", weight: 9, answer_id: nil},
  {id: 281, keyword: "Making", weight: 7, answer_id: nil},
  {id: 282, keyword: "Nerdy", weight: 5, answer_id: nil},
  {id: 284, keyword: "Lazy", weight: 7, answer_id: nil},
  {id: 285, keyword: "Indoors", weight: 6, answer_id: nil},
  {id: 286, keyword: "Active", weight: 8, answer_id: nil},
  {id: 287, keyword: "Clear Purpose", weight: 7, answer_id: nil},
  {id: 288, keyword: "Strong Community", weight: 7, answer_id: nil},
  {id: 289, keyword: "Art", weight: 1, answer_id: nil},
  {id: 290, keyword: "Nerdy", weight: 10, answer_id: nil},
  {id: 291, keyword: "Technology", weight: 8, answer_id: nil},
  {id: 292, keyword: "Computers", weight: 8, answer_id: nil},
  {id: 293, keyword: "Science", weight: 3, answer_id: nil},
  {id: 294, keyword: "Making", weight: 3, answer_id: nil},
  {id: 295, keyword: "Gaming", weight: 8, answer_id: nil},
  {id: 296, keyword: "Lazy", weight: 7, answer_id: nil},
  {id: 297, keyword: "Engineering", weight: 4, answer_id: nil},
  {id: 298, keyword: "Great Advisor", weight: 4, answer_id: nil},
  {id: 299, keyword: "Musical", weight: 10, answer_id: 30},
  {id: 300, keyword: "Creative", weight: 3, answer_id: 30},
  {id: 301, keyword: "Musical", weight: 10, answer_id: nil},
  {id: 302, keyword: "Strong Community", weight: 4, answer_id: nil},
  {id: 303, keyword: "Indoors", weight: 4, answer_id: nil},
  {id: 304, keyword: "Active", weight: 10, answer_id: nil},
  {id: 305, keyword: "Outdoors", weight: 10, answer_id: nil},
  {id: 306, keyword: "Sports", weight: 2, answer_id: nil},
  {id: 307, keyword: "Competitive", weight: 2, answer_id: nil},
  {id: 308, keyword: "Physics", weight: 10, answer_id: nil},
  {id: 309, keyword: "Major-focused", weight: 8, answer_id: nil},
  {id: 310, keyword: "Science", weight: 8, answer_id: nil},
  {id: 311, keyword: "Lazy", weight: 6, answer_id: nil},
  {id: 312, keyword: "Outdoors", weight: 6, answer_id: nil},
  {id: 313, keyword: "Activism", weight: 8, answer_id: nil},
  {id: 314, keyword: "Major-focused", weight: 8, answer_id: nil},
  {id: 315, keyword: "Major-focused", weight: 9, answer_id: nil},
  {id: 316, keyword: "Activism", weight: 2, answer_id: nil},
  {id: 317, keyword: "Nerdy", weight: 9, answer_id: nil},
  {id: 318, keyword: "Lazy", weight: 9, answer_id: nil},
  {id: 319, keyword: "Gaming", weight: 9, answer_id: nil},
  {id: 320, keyword: "Clear Purpose", weight: 6, answer_id: nil},
  {id: 321, keyword: "Sports", weight: 9, answer_id: nil},
  {id: 322, keyword: "Competitive", weight: 9, answer_id: nil},
  {id: 323, keyword: "Self-directed", weight: 7, answer_id: nil},
  {id: 325, keyword: "Olympics", weight: 5, answer_id: nil},
  {id: 326, keyword: "Major-focused", weight: 8, answer_id: nil},
  {id: 327, keyword: "Activism", weight: 2, answer_id: nil},
  {id: 328, keyword: "Nerdy", weight: 3, answer_id: nil},
  {id: 329, keyword: "Lazy", weight: 2, answer_id: nil},
  {id: 330, keyword: "Indoors", weight: 5, answer_id: nil},
  {id: 331, keyword: "Not Social", weight: 4, answer_id: nil}
])
Officer.create!([
  {id: 1, first: "Charlie", last: "Hanacek", email: "charlie@email.com", phone: "555-555-5555"},
  {id: 2, first: "Tyler", last: "Walker", email: "tyler@email.com", phone: "555-555-5555"}
])
OfficerRso.create!([
  {id: 1, officer_id: 1, rso_id: 21},
  {id: 2, officer_id: 2, rso_id: 21},
  {id: 3, officer_id: 1, rso_id: 18},
  {id: 4, officer_id: 2, rso_id: 11},
  {id: 5, officer_id: 1, rso_id: 26},
  {id: 6, officer_id: 1, rso_id: 5}
])
Question.create!([
  {id: 1, question_title: "Do you enjoy cooking?", position: 1},
  {id: 2, question_title: "Do you enjoy science?", position: 2},
  {id: 4, question_title: "Are you introverted or extroverted?", position: 3},
  {id: 5, question_title: "How might you spend a typical Saturday night?", position: 4},
  {id: 6, question_title: "What would you value most in a club?", position: 5},
  {id: 7, question_title: "Are you interested in doing something active?", position: 6},
  {id: 8, question_title: "Are you interested in doing something creative", position: 7},
  {id: 9, question_title: "Are you interested in technology?", position: 8},
  {id: 10, question_title: "Do you like the Olympics?", position: 9},
  {id: 11, question_title: "Are you interested in academic clubs (clubs that are focused around a specific major or group of majors)?", position: 10},
  {id: 12, question_title: "Are you an activist?", position: 11},
  {id: 13, question_title: "Do you play an instrument?", position: 12}
])
Response.create!([
  {id: 1}
])
Rso.create!([
  {id: 1, name: "Association of Computer Machinery", nickname: "ACM"},
  {id: 2, name: "Linux Users Group", nickname: "LUG"},
  {id: 3, name: "Knitting Club", nickname: "KNIT"},
  {id: 4, name: "Mountain Biking Club", nickname: "MBC"},
  {id: 5, name: "Sportsmans club", nickname: "SC"},
  {id: 6, name: "Black Student Union", nickname: "BSU"},
  {id: 7, name: "Geology Club", nickname: "WSUGeoClub"},
  {id: 8, name: "Environmental Science Club", nickname: "ESC"},
  {id: 9, name: "The Criminal Justice Club", nickname: "CJ Club"},
  {id: 10, name: "Humans vs Zombies", nickname: "HvZ"},
  {id: 11, name: "Physics and Astronomy Club", nickname: "Physics"},
  {id: 12, name: "Floor Hockey Club", nickname: "Floor Hockey"},
  {id: 13, name: "Smash Bros Club", nickname: "SBC"},
  {id: 14, name: "Digital Media Club", nickname: "DMC"},
  {id: 15, name: "Biology Club", nickname: "Bio Club"},
  {id: 16, name: "Pre Law Society", nickname: "PLS"},
  {id: 17, name: "Food Science Club", nickname: "FS Club"},
  {id: 18, name: "Horticulture Club", nickname: "Hort Club"},
  {id: 19, name: "Judo Club", nickname: "Judo @ WSU"},
  {id: 20, name: "Low Brass Collective", nickname: "LBC"},
  {id: 21, name: "Archery Club", nickname: "Archery"},
  {id: 22, name: "WSU Chess", nickname: "WSUC"},
  {id: 23, name: "Latin Dance Club", nickname: "LDC"},
  {id: 24, name: "Cougs in Space", nickname: "CiS"},
  {id: 25, name: "Esports and Gaming", nickname: "EGWSU"},
  {id: 26, name: "Political Science Club", nickname: "PSCWSU"}
])
RsoKeyword.create!([
  {id: 1, rso_id: 21, keyword_id: 209},
  {id: 2, rso_id: 21, keyword_id: 210},
  {id: 3, rso_id: 21, keyword_id: 211},
  {id: 4, rso_id: 21, keyword_id: 212},
  {id: 5, rso_id: 21, keyword_id: 213},
  {id: 6, rso_id: 21, keyword_id: 214},
  {id: 7, rso_id: 1, keyword_id: 215},
  {id: 8, rso_id: 1, keyword_id: 216},
  {id: 9, rso_id: 1, keyword_id: 217},
  {id: 10, rso_id: 1, keyword_id: 218},
  {id: 11, rso_id: 1, keyword_id: 219},
  {id: 12, rso_id: 1, keyword_id: 220},
  {id: 13, rso_id: 15, keyword_id: 221},
  {id: 14, rso_id: 15, keyword_id: 222},
  {id: 15, rso_id: 15, keyword_id: 223},
  {id: 16, rso_id: 1, keyword_id: 224},
  {id: 17, rso_id: 1, keyword_id: 225},
  {id: 18, rso_id: 6, keyword_id: 226},
  {id: 19, rso_id: 6, keyword_id: 227},
  {id: 20, rso_id: 24, keyword_id: 228},
  {id: 21, rso_id: 24, keyword_id: 229},
  {id: 22, rso_id: 24, keyword_id: 230},
  {id: 23, rso_id: 24, keyword_id: 231},
  {id: 24, rso_id: 24, keyword_id: 232},
  {id: 25, rso_id: 24, keyword_id: 233},
  {id: 26, rso_id: 24, keyword_id: 234},
  {id: 27, rso_id: 24, keyword_id: 235},
  {id: 28, rso_id: 14, keyword_id: 236},
  {id: 29, rso_id: 14, keyword_id: 237},
  {id: 30, rso_id: 14, keyword_id: 238},
  {id: 31, rso_id: 14, keyword_id: 239},
  {id: 32, rso_id: 14, keyword_id: 240},
  {id: 33, rso_id: 14, keyword_id: 241},
  {id: 34, rso_id: 14, keyword_id: 242},
  {id: 35, rso_id: 8, keyword_id: 243},
  {id: 36, rso_id: 8, keyword_id: 244},
  {id: 37, rso_id: 8, keyword_id: 245},
  {id: 38, rso_id: 8, keyword_id: 246},
  {id: 39, rso_id: 8, keyword_id: 247},
  {id: 40, rso_id: 8, keyword_id: 248},
  {id: 41, rso_id: 8, keyword_id: 249},
  {id: 42, rso_id: 25, keyword_id: 250},
  {id: 43, rso_id: 25, keyword_id: 251},
  {id: 44, rso_id: 25, keyword_id: 252},
  {id: 45, rso_id: 25, keyword_id: 253},
  {id: 46, rso_id: 12, keyword_id: 254},
  {id: 47, rso_id: 12, keyword_id: 255},
  {id: 48, rso_id: 12, keyword_id: 256},
  {id: 49, rso_id: 12, keyword_id: 257},
  {id: 50, rso_id: 12, keyword_id: 258},
  {id: 51, rso_id: 12, keyword_id: 259},
  {id: 52, rso_id: 17, keyword_id: 260},
  {id: 53, rso_id: 17, keyword_id: 261},
  {id: 54, rso_id: 17, keyword_id: 262},
  {id: 55, rso_id: 17, keyword_id: 263},
  {id: 56, rso_id: 17, keyword_id: 264},
  {id: 57, rso_id: 7, keyword_id: 265},
  {id: 58, rso_id: 1, keyword_id: 266},
  {id: 59, rso_id: 7, keyword_id: 267},
  {id: 60, rso_id: 7, keyword_id: 268},
  {id: 61, rso_id: 7, keyword_id: 269},
  {id: 62, rso_id: 18, keyword_id: 270},
  {id: 63, rso_id: 18, keyword_id: 271},
  {id: 64, rso_id: 18, keyword_id: 272},
  {id: 65, rso_id: 10, keyword_id: 273},
  {id: 66, rso_id: 10, keyword_id: 274},
  {id: 67, rso_id: 10, keyword_id: 275},
  {id: 68, rso_id: 10, keyword_id: 276},
  {id: 69, rso_id: 10, keyword_id: 277},
  {id: 70, rso_id: 19, keyword_id: 278},
  {id: 71, rso_id: 19, keyword_id: 279},
  {id: 72, rso_id: 19, keyword_id: 280},
  {id: 73, rso_id: 3, keyword_id: 281},
  {id: 74, rso_id: 3, keyword_id: 282},
  {id: 75, rso_id: 3, keyword_id: 283},
  {id: 76, rso_id: 3, keyword_id: 284},
  {id: 77, rso_id: 3, keyword_id: 285},
  {id: 78, rso_id: 23, keyword_id: 286},
  {id: 79, rso_id: 23, keyword_id: 287},
  {id: 80, rso_id: 23, keyword_id: 288},
  {id: 81, rso_id: 23, keyword_id: 289},
  {id: 82, rso_id: 2, keyword_id: 290},
  {id: 83, rso_id: 2, keyword_id: 291},
  {id: 84, rso_id: 2, keyword_id: 292},
  {id: 85, rso_id: 2, keyword_id: 293},
  {id: 86, rso_id: 2, keyword_id: 294},
  {id: 87, rso_id: 2, keyword_id: 295},
  {id: 88, rso_id: 2, keyword_id: 296},
  {id: 89, rso_id: 2, keyword_id: 297},
  {id: 90, rso_id: 2, keyword_id: 298},
  {id: 91, rso_id: 20, keyword_id: 301},
  {id: 92, rso_id: 20, keyword_id: 302},
  {id: 93, rso_id: 20, keyword_id: 303},
  {id: 94, rso_id: 4, keyword_id: 304},
  {id: 95, rso_id: 4, keyword_id: 305},
  {id: 96, rso_id: 4, keyword_id: 306},
  {id: 97, rso_id: 4, keyword_id: 307},
  {id: 98, rso_id: 11, keyword_id: 308},
  {id: 99, rso_id: 11, keyword_id: 309},
  {id: 100, rso_id: 11, keyword_id: 310},
  {id: 101, rso_id: 11, keyword_id: 311},
  {id: 102, rso_id: 11, keyword_id: 312},
  {id: 103, rso_id: 26, keyword_id: 313},
  {id: 104, rso_id: 26, keyword_id: 314},
  {id: 105, rso_id: 16, keyword_id: 315},
  {id: 106, rso_id: 16, keyword_id: 316},
  {id: 107, rso_id: 13, keyword_id: 317},
  {id: 108, rso_id: 13, keyword_id: 318},
  {id: 109, rso_id: 13, keyword_id: 319},
  {id: 110, rso_id: 13, keyword_id: 320},
  {id: 111, rso_id: 5, keyword_id: 321},
  {id: 112, rso_id: 5, keyword_id: 322},
  {id: 113, rso_id: 5, keyword_id: 323},
  {id: 114, rso_id: 5, keyword_id: 324},
  {id: 115, rso_id: 5, keyword_id: 325},
  {id: 116, rso_id: 9, keyword_id: 326},
  {id: 117, rso_id: 9, keyword_id: 327},
  {id: 118, rso_id: 22, keyword_id: 328},
  {id: 119, rso_id: 22, keyword_id: 329},
  {id: 120, rso_id: 22, keyword_id: 330},
  {id: 121, rso_id: 22, keyword_id: 331}
])
