Keyword::HABTM_Rsos.create!([
  {keyword_id: 13, rso_id: 1},
  {keyword_id: 14, rso_id: 1},
  {keyword_id: 15, rso_id: 1},
  {keyword_id: 16, rso_id: 1}
])
Rso::HABTM_Keywords.create!([
  {keyword_id: 13, rso_id: 1},
  {keyword_id: 14, rso_id: 1},
  {keyword_id: 15, rso_id: 1},
  {keyword_id: 16, rso_id: 1}
])
Answer.create!([
  {answer_title: "Board Game", question_id: 1, position: 2, response_id: nil},
  {answer_title: "Go Biking", question_id: 1, position: 1, response_id: nil},
  {answer_title: "Painting", question_id: 2, position: 1, response_id: nil},
  {answer_title: "Gaming", question_id: 2, position: 1, response_id: nil},
  {answer_title: "Knit Something", question_id: 3, position: 1, response_id: nil},
  {answer_title: "Write an Algorithm", question_id: 3, position: 1, response_id: nil},
  {answer_title: "Go Out", question_id: 4, position: 1, response_id: nil},
  {answer_title: "Stay In", question_id: 4, position: 1, response_id: nil},
  {answer_title: "Charity Bike Race", question_id: 5, position: 1, response_id: nil},
  {answer_title: "Write Novel", question_id: 5, position: 1, response_id: nil},
  {answer_title: "Dancing", question_id: 6, position: 1, response_id: nil},
  {answer_title: "Walking on the Beach", question_id: 6, position: 1, response_id: nil}
])
Keyword.create!([
  {keyword: "Gaming", weight: 6, answer_id: 1},
  {keyword: "Physical", weight: 6, answer_id: 2},
  {keyword: "Artistic", weight: 6, answer_id: 3},
  {keyword: "Gaming", weight: 3, answer_id: 4},
  {keyword: "Artistic", weight: 6, answer_id: 5},
  {keyword: "Science", weight: 6, answer_id: 6},
  {keyword: "Social", weight: 6, answer_id: 7},
  {keyword: "Introverted", weight: 6, answer_id: 8},
  {keyword: "Charity", weight: 6, answer_id: 9},
  {keyword: "Creative", weight: 6, answer_id: 10},
  {keyword: "Active", weight: 6, answer_id: 11},
  {keyword: "Active", weight: 6, answer_id: 12},
  {keyword: "Gaming", weight: 6, answer_id: nil},
  {keyword: "Technology", weight: 10, answer_id: nil},
  {keyword: "Computers", weight: 10, answer_id: nil},
  {keyword: "Community", weight: 2, answer_id: nil}
])
Officer.create!([
  {first: "Nick", last: "Vasicek", email: "nick@email.com", phone: "555-555-5555"},
  {first: "Charlie", last: "Hanacek", email: "charlie@email.com", phone: "555-555-5555"},
  {first: "Tyler", last: "Walker", email: "tyler@email.com", phone: "555-555-5555"}
])
OfficerRso.create!([
  {officer_id: 1, rso_id: 1},
  {officer_id: 2, rso_id: 1},
  {officer_id: 1, rso_id: 2},
  {officer_id: 2, rso_id: 2},
  {officer_id: 3, rso_id: 2},
  {officer_id: 2, rso_id: 3},
  {officer_id: 1, rso_id: 4},
  {officer_id: 2, rso_id: 4},
  {officer_id: 1, rso_id: 5},
  {officer_id: 2, rso_id: 5},
  {officer_id: 1, rso_id: 6},
  {officer_id: 2, rso_id: 6},
  {officer_id: 1, rso_id: 7},
  {officer_id: 2, rso_id: 7},
  {officer_id: 1, rso_id: 9},
  {officer_id: 2, rso_id: 9},
  {officer_id: 1, rso_id: 10},
  {officer_id: 2, rso_id: 10},
  {officer_id: 1, rso_id: 11},
  {officer_id: 2, rso_id: 11},
  {officer_id: 1, rso_id: 12},
  {officer_id: 2, rso_id: 12},
  {officer_id: 1, rso_id: 13},
  {officer_id: 2, rso_id: 13},
  {officer_id: 2, rso_id: 14},
  {officer_id: 3, rso_id: 14},
  {officer_id: 3, rso_id: 15},
  {officer_id: 2, rso_id: 16},
  {officer_id: 2, rso_id: 17},
  {officer_id: 1, rso_id: 18},
  {officer_id: 3, rso_id: 19},
  {officer_id: 1, rso_id: 20},
  {officer_id: 3, rso_id: 20},
  {officer_id: 3, rso_id: 21},
  {officer_id: 2, rso_id: 21},
  {officer_id: 1, rso_id: 22},
  {officer_id: 2, rso_id: 23},
  {officer_id: 1, rso_id: 24},
  {officer_id: 2, rso_id: 25},
  {officer_id: 1, rso_id: 26},
  {officer_id: 2, rso_id: 26},
  {officer_id: 3, rso_id: 26},
  {officer_id: 1, rso_id: 27},
  {officer_id: 2, rso_id: 27},
  {officer_id: 3, rso_id: 27}
])
Question.create!([
  {question_title: "Play a board game or go biking?", position: 3},
  {question_title: "Painting or gaming?", position: 1},
  {question_title: "Knit something or write an algorithm?", position: 2},
  {question_title: "Go out or stay in?", position: 4},
  {question_title: "Charity bike race or write novel?", position: 5},
  {question_title: "Dancing or walking on the beach?", position: 6}
])
Rso.create!([
  {name: "Association of Computer Machinery", nickname: "ACM"},
  {name: "Linux Users Group", nickname: "LUG"},
  {name: "Knitting Club", nickname: "KNIT"},
  {name: "Mountain Biking Club", nickname: "MBC"},
  {name: "Sportsmans club", nickname: "SC"},
  {name: "Black Student Union", nickname: "BSU"},
  {name: "Geology Club", nickname: "WSUGeoClub"},
  {name: "Environmental Science Club", nickname: "ESC"},
  {name: "The Criminal Justice Club", nickname: "CJ Club"},
  {name: "Humans vs Zombies", nickname: "HvZ"},
  {name: "Physics and Astronomy Club", nickname: "Physics"},
  {name: "Floor Hockey Club", nickname: "Floor Hockey"},
  {name: "Smash Bros Club", nickname: "SBC"},
  {name: "Digital Media Club", nickname: "DMC"},
  {name: "Biology Club", nickname: "Bio Club"},
  {name: "Pre Law Society", nickname: "PLS"},
  {name: "Food Science Club", nickname: "FS Club"},
  {name: "Horticulture Club", nickname: "Hort Club"},
  {name: "Judo Club", nickname: "Judo @ WSU"},
  {name: "Low Brass Collective", nickname: "LBC"},
  {name: "Archery Club", nickname: "Archery"},
  {name: "WSU Chess", nickname: "WSUC"},
  {name: "Latin Dance Club", nickname: "LDC"},
  {name: "Cougs in Space", nickname: "CiS"},
  {name: "Esports and Gaming", nickname: "EGWSU"},
  {name: "Political Science Club", nickname: "PSCWSU"}
])
